### ISSUE TITLE
why this block?

### ISSUE THREAD

**Issue by iperov** [fdbtrs/mixfacenets#3]
![firefox_2021-08-03_09-13-57](https://user-images.githubusercontent.com/8076202/127961473-ceb226cc-3b1d-4feb-9e05-a8361ffa0140.png)

it is the same as just single 1x1xc conv.

**Comment by fdbtrs** [comment]
It is not the same as a single 1x1 conv. there are 2 kernel in this block

**Comment by iperov** [comment]
same as single conv with groups=2

https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html

![firefox_2021-08-10_09-06-02](https://user-images.githubusercontent.com/8076202/128811110-5e6baee7-8b76-4297-8874-9efa54e5892d.png)
