### ISSUE TITLE
Underwelming results of eval.py

### ISSUE THREAD

**Issue by stbunda** [fdbtrs/mixfacenets#6]
Hello,

I tried to run the eval.py using the evaluation dataset (MS1M-ArcFace), but the results for the MixFaceNet-S are suboptimal...

**Log file**:
Training: 2021-09-16 10:52:06,829-[lfw][295672]XNorm: 289.635608
Training: 2021-09-16 10:52:06,837-[lfw][295672]Accuracy-Flip: 0.58800+-0.01770
Training: 2021-09-16 10:52:06,837-[lfw][295672]Accuracy-Highest: 0.58800
Training: 2021-09-16 10:55:39,481-[cfp_fp][295672]XNorm: 2203.600646
Training: 2021-09-16 10:55:39,481-[cfp_fp][295672]Accuracy-Flip: 0.50171+-0.01464
Training: 2021-09-16 10:55:39,481-[cfp_fp][295672]Accuracy-Highest: 0.50171
Training: 2021-09-16 10:58:48,704-[agedb_30][295672]XNorm: 434.067380
Training: 2021-09-16 10:58:48,705-[agedb_30][295672]Accuracy-Flip: 0.49850+-0.00444
Training: 2021-09-16 10:58:48,705-[agedb_30][295672]Accuracy-Highest: 0.49850

I used the '295672backbone.pth' in the output folder.

Thanks for the help in advance!

**Comment by fdbtrs** [comment]
Please make sure that you are using the correct configurations for loading the backbone e.g. for ShuffleMixFaceNet-S the parameters are: embedding:512, width scale:1, gdw_size: 1024 and shuffle: True.

**Comment by Wonder1905** [comment]
Hi, Im having the same issue,  following the exact instruction as asked, the weights are loaded perfectly, and the results are random. Its important to mention that the embedddings are huge, so its seems as something is problematic.
Can you share the data you used, maybe it is some different distribution.
